# Generated by Django 3.0.6 on 2020-05-30 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=100)),
                ('act_nr', models.CharField(max_length=100)),
                ('act_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('creditor_name', models.CharField(max_length=100)),
                ('invoice_series', models.CharField(max_length=10)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('responsible_member', models.CharField(max_length=100)),
                ('main_member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissioner', to=settings.AUTH_USER_MODEL)),
                ('member1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissioner4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
