# Generated by Django 3.0.6 on 2020-05-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200530_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('VNT', 'vnt.'), ('KOMPL', 'kompl.')], default='VNT', max_length=5)),
                ('cost', models.FloatField()),
                ('sum', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Form')),
            ],
        ),
    ]
